COMMUNITY_TO_SYSTEM = {
    5: "Psychiatric & Neurological System",
    6: "Dermatological/Integumentary System",
    0: "Musculoskeletal & Reproductive System",
    1: "Gastrointestinal System",
    2: "Cardiovascular & Respiratory System",
    8: "Genitourinary System",
    4: "Ophthalmological System",
    48: "Obstetric & Sexual/Behavioral System",
    40: "Psychiatric System",
    58: "Dental/Maxillofacial System"
}

NON_SYMPTOMS = [
    "clean surface", "the lesions are characterized by white", "out significant raised skin",
    "some showing pigmentation", "commonly found in anterior premolars", "elevated above the skin)",
    "each other", "-like pattern appearing prior to the rash", "pain. in later stages", "is fixed",
    "increased distance between the first", "more than half of the cases", "extension movement",
    "self-relieving after several months", "abdominal intercostal areas", "may not show noticeable clinical symptoms",
    "out sound or", "swollen gl", "poor response", "iosity", "erect normally",
    "a history of hypertension may experience discomfort in the head", "in a relatively weakened state",
    "or obvious signs of fractures", "initial presentation includes fever", "out any drops of urine",
    "polyuria)", "worsening over time", "chemical substances", "mtx", "the lesions are soaked",
    "upper body normal", "for towels or bed covers)", "i.e", "which grows rapidly",
    "such as saying 'ear' as 'ear guo'", "which then forms an ulcer covered", "a white exudate",
    "the base of which may have bleeding points. when the lesions invade deeper structures",
    "they can cause destruction of the epiglottis", "uvula", "leading to perforation",
    "in 3-10 years after infection", "it often leads to weak uterine contractions",
    "ibular retrusion", "are of normal skin color", "ibular prognathism", "trauma",
    "or insect bite-like changes", "ering superficial veins", "pain or drawing pain", "superficial streaky b",
    "iosity",
    "each other",
    "more than half of the cases",
    "erect normally",
    "in a relatively weakened state",
    "self-relieving after several months",
    "commonly found in anterior premolars",
    "some showing pigmentation",
    "elevated above the skin)",
    "poor response",
    "blunt angle of m",
    "impacting st",
    "for towels or bed covers)",
    "i.e",
    "upper body normal",
    "the lesions are characterized by white",
    "the lesions are soaked",
    "which grows rapidly",
    "such as saying 'ear' as 'ear guo'"
]